### ISSUE TITLE
[Bug]: RK3399 无法正常安装win11镜像

### ISSUE THREAD

**Issue by 15169670031** [dockur/windows-arm#233]
### Operating system

armbian(Ubuntu20.04.2 LTS (Focal Fossa) )

### Description

安装看起来一切正常，直到出现start boot option然后所有的按键都无效
![Snipaste_2024-11-28_10-36-27](https://github.com/user-attachments/assets/64669890-91a1-4af6-bf97-6897360ae8f1)

### Docker compose

docker run -it --rm -p 8006:8006 --device=/dev/kvm --cap-add NET_ADMIN -e RAM_SIZE="2G" -d --stop-timeout 120 dockurr/windows

### Docker log

❯ Starting Windows for Docker v4.05...
❯ For support visit https://github.com/dockur/windows-arm
❯ CPU: Cortex A53 | RAM: 2/4 GB | DISK: 52 GB (ext4) | KERNEL: 5.10.60-rockchip64...

❯ Requesting Windows 11 from the Microsoft servers...
❯ Downloading Windows 11...

/storage/tmp/win11arm64.iso     0%[                                               ]       0  --.-KB/s               
/storage/tmp/win11arm64.iso   100%[==============================================>]   5.08G  15.8MB/s    in 4m 58s  
❯ Extracting Windows 11 image...
❯ Adding drivers to image...
❯ Adding win11arm64.xml for automatic installation...
[1;34m❯ Building Windows 11 image...
❯ Creating a 64G growable disk image in raw format...
❯ Warning: your configured RAM_SIZE of 2 GB is very close to the 2 GB of memory available, please consider a lower value.
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found

BdsDxe: loading Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:01.0-3" from PciRoot(0x0)/Pci(0x1,0x0)/USB(0x2,0x0)

BdsDxe: starting Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:01.0-3" from PciRoot(0x0)/Pci(0x1,0x0)/USB(0x2,0x0)

❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

### Screenshots (optional)

![Snipaste_2024-11-28_10-36-27](https://github.com/user-attachments/assets/6d70a78b-6e5d-4d0b-b36d-b296b896f3ac)

**Comment by ravenrcl** [comment]
I have the same error on Oracle Cloud AMPERE ARM based VMs.  Oracle 8 and Ubuntu have the same problem.  It apparently doesn't have KVM support, so I have the following for the compose.yml. I know it will be slow, just testing to get  SOMETHING besides nginx to work.
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      KVM: "N"
      HV: "N"
    devices:
      # - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 3458:8006
      - 3459:3389/tcp
      - 3459:3389/udp
    stop_grace_period: 2m

**Comment by ravenrcl** [comment]
fixed with a different image.  Still very slow of course, but it works.
....................
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/tiny11a64/tiny11a64 r1.iso"
      KVM: "N"
      HV: "N"
    devices:
      # - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 3458:8006
      - 3459:3389/tcp
      - 3459:3389/udp
    stop_grace_period: 2m

**Comment by coaxialdaisy** [comment]
Same issue here. 

Hardware: RSPI Pi4b 8G
HD: M.2 1TB SSD through USB3 (Bus 002 Device 002: ID 0bda:9210 Realtek Semiconductor Corp. RTL9210 M.2 NVME Adapter)
OS: Bookworm 64bit (6.6.62+rpt-rpi-v8)
Docker engine:	27.5.1 (API: 1.47)

**Comment by coaxialdaisy** [comment]
> Same issue here. 
> 
> Hardware: RSPI Pi4b 8G
> HD: M.2 1TB SSD through USB3 (Bus 002 Device 002: ID 0bda:9210 Realtek Semiconductor Corp. RTL9210 M.2 NVME Adapter)
> OS: Bookworm 64bit (6.6.62+rpt-rpi-v8)
> Docker engine:	27.5.1 (API: 1.47)

I can install Windows 10 without any issues. Wil try to upgrade to win11 later.

P.S.: The error message still appears, but the installation process continues successfully.
